{% set name = "libtasn1" %}
{% set version = "4.17.0" %}
{% set sha256 = "ece7551cea7922b8e10d7ebc70bc2248d1fdd73351646a2d6a8d68a9421c45a5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://ftp.gnu.org/gnu/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - fix-clang-test-failures.patch       # [osx]

build:
  number: 0
  # seems Windows with MSVC not currently supported
  skip: True  # [win]
  run_exports:
    # Nice, stable ABI: https://abi-laboratory.pro/?view=timeline&l=libtasn1
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - make    # [unix]
  host:
  run:

test:
  commands:
    - test -f $PREFIX/lib/libtasn1${SHLIB_EXT}  # [unix]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://www.gnu.org/software/libtasn1/
  license: GPL-3.0
  license_file: LICENSE
  summary: 'Libtasn1 is the ASN.1 library used by GnuTLS, p11-kit and some other packages'
  description: |
    The Libtasn1 library provides Abstract Syntax Notation One
    (ASN.1, as specified by the X.680 ITU-T recommendation) parsing and structures management,
    and Distinguished Encoding Rules (DER, as per X.690) encoding and decoding functions.
  doc_url: https://www.gnu.org/software/libtasn1/manual/libtasn1.html
  dev_url: https://gitlab.com/gnutls/libtasn1/

extra:
  recipe-maintainers:
    - gillins
    - ceholden
    - ocefpaf
    - chenghlee
