{% set name = "libtasn1" %}
{% set version = "4.20.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://ftpmirror.gnu.org/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 92e0e3bd4c02d4aeee76036b2ddd83f0c732ba4cda5cb71d583272b23587a76c

build:
  number: 0
  # seems Windows with MSVC not currently supported
  skip: True  # [win]
  run_exports:
    # Nice, stable ABI: https://abi-laboratory.pro/?view=timeline&l=libtasn1
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - make    # [unix]
    - libtool  # [unix]

test:
  requires:
  # For conda inspect command
    - conda-build  # [osx]

  commands:
    - ls -l "${PREFIX}/bin" || true             # [unix]
    - command -v asn1Parser                     # [unix]
    - asn1Parser --version                      # [unix]
    - command -v asn1Coding && asn1Coding --help || true  # [unix]
    - test -f $PREFIX/lib/libtasn1${SHLIB_EXT}  # [unix]
    - test -f ${PREFIX}/include/libtasn1.h      # [unix]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://www.gnu.org/software/libtasn1
  license_family: LGPL
  license: LGPL-2.1-or-later
  license_file: COPYING
  summary: 'Libtasn1 is the ASN.1 library used by GnuTLS, p11-kit and some other packages'
  description: |
    The Libtasn1 library provides Abstract Syntax Notation One
    (ASN.1, as specified by the X.680 ITU-T recommendation) parsing and structures management,
    and Distinguished Encoding Rules (DER, as per X.690) encoding and decoding functions.
  doc_url: https://www.gnu.org/software/libtasn1/manual/libtasn1.html
  dev_url: https://gitlab.com/gnutls/libtasn1

extra:
  recipe-maintainers:
    - gillins
    - ceholden
    - ocefpaf
    - chenghlee
