travis:
  secure:
    BINSTAR_TOKEN: iDvoHhypza58Lybwz+QUnIzxs1nOQxGMsPTTnBc/kuRwaY21mdxNy1SaG2bG9xrYbLe1QF6PbTd6eIa3agEwefYTCaWeEHK8IISn+yG2UnAXjTfHSsKhf2FrpoZwbzeIFIOgyOBsbHgGLOsgrpTFGnKgSzdes9Gmh1ZGFGJiUd1LKrCtI8VHkK2nrrTT21ikQy5FrzknBytKMEB3qrKld4UK9USEyHcoiAb0baCWoEdVXzmPtHiIUFUqxpF5l7GY+H8527hJdFU3FT8aLJjp4GcZGP7Jpc4PdJivS94dJjROS7IRMk6sfl4cnqUC28OSGDpeEuuAb4RtkIssWo3NFb+308yYfHWXzq6QI575PuPOvaT6T7vmiL5b2OELje3diShvEx3bYF/OeULVnNxUla+jrnEBZJoPM1wBt1L7LwVfQO3xyIR86i0lAhdHp2aGs2FXeAKhs9TSnTdJFaJP7Q3Pita3F1OBUysW4UAQHBjXRzoZJBt0nHAJ2EdrBBttibSMsihXx+DDpFjg5lL25hX6k4zaC2m9pdrMU2go2YNDo2qfQkke0ojsXwuPdF3f50mOXKJdvp8KbwMAe/CjXlUqINR9j8MTV0HTnm3OrrE2ifBMGlLzmdrBz3hi12gHqTUtoA2I+/eK4KBTcvYDab36Amg3sIN2FRDjevbahvc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
